version: 2.1

cache_key: &cache_key typescript-stdlib-20201125-{{ checksum "pnpm-lock.yaml" }}

jobs:
  lint-build-test:
    docker:
      - image: cszatmary/cimg-node:20
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm cache
          keys:
            - *cache_key
      - run:
          name: Install dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          name: Save pnpm cache
          key: *cache_key
          paths:
            - node_modules/
      - run:
          name: Setup project
          command: pnpm run setup
      - run:
          name: Ensure no dependencies
          command: pnpm run ensure-no-deps
      - run:
          name: Run linter
          command: pnpm run lint
      - run:
          name: Check types
          command: pnpm run check-types
      - run:
          name: Build library for targets
          command: pnpm run build
      - run:
          name: Run deno tests
          command: pnpm run test:deno
      - run:
          name: Run node tests
          command: pnpm run test:node:ci
      - run:
          name: Run e2e tests
          command: pnpm run e2e

workflows:
  build-test:
    jobs:
      - lint-build-test:
          filters:
            branches:
              ignore:
                - deno-latest
